export const comitetConsultativ = [
    "ector: Ramona Lile",
    "rorector: Codruta Stoica",
    "rorector: Popa Alexandru",
    "rorector: Teodor Cilan",
    "Decan - Facultatea de Inginerie: Dan Glavan",
    "rodecan: Doina Mortoiu",
    "rodecan: Adina Bucevschi",
    "irector de departament: Gheorghe Sima",
  ];
  
  export const comitetStiintific = [
    "Acad. Florin Gheorghe Filip (Romania)",
    "Valeriu Beiu (Romania)",
    "Michio Sugeno (Japonia)",
    "Lakhmi C. Jain (Australia)",
    "Anca Ralescu (USA)",
    "Dan Ralescu (USA)",
    "Guojun Wang (China)",
    "Bernadette Bouchon-Meunier (Franta)",
    "Salil Bose (USA)",
    "Ioan Dzitac (Romania)",
    "Tsung-Chih Lin (China)",
    "Octavian Prostean (Romania)",
    "Oana Geman (Romania)",
    "Ankur Gupta (India)",
    "Gheorghe Capatana (Republica Moldova)",
    "Muhammad Waseem Ashraf (Pakistan)",
    "Simona Dzitac (Romania)",
    "Gelu Ovidiu Tirian (Romania)",
    "Mariana Nagy (Romania)",
    "Rajeeb Dey (India)",
    "Seshadhri Srinivasan (India)",
    "Muhammad Waseem Ashraf (Pakistan)",
    "Nilanjan Dey (India)",
    "Amira Ashour (Egipt)",
    "Fuqian Shi (China)",
    "Barnali Dey (India)",
    "Krit Salahddine (Maroc)",
    "Bhuvan Modi (USA)",
    "Muhammad Arif (China)",
    "Ranbir Batth (India)",
    ">Muhammad Imran Tariq (Pakistan)",
    "Mohit Mittal (India)",
    "Rob Raluca (Romania)",
    "Cornelia Victoria Anghel Drugarin (Romania)",
    "Roxana Beiu (Romania)",
    "Clara Rohatinovici (Romania)",
    "Kristijan Cincar (Serbia)",
    "Marius Buzera (Romania)",
    "Maria Petcut (Romania)",
    "Maria Muresan (Romania)",
    "Florina Pasculescu (Romania)",
    "Carmen Rus (Romania)",
  ];
  
  export const comidetDeOrganizare = [
    " Marius M. Balas",
    "Valentina E. Balas",
    "Virgil F. Duma",
    "Valentin Muller",
    "Corina Mnerie",
    "Ioan Koles",
    "Cornel Barna",
    "Mihaela Popa",
    "Daniel Dragu",
    "Noemi Clara Rohatinovici",
  ];
  
  export const sectiuneaMecanica = [
    "Ioan Radu",
    "Iosif Kaposta",
    "Liviu Sevastian Bocii",
    "Adriana Motica",
    "Gheorghe Hutiu",
    "Dorin Demian",
    "Lucian Gal",
    "Bogdan Tanasoiu",
    "Aurelia Tanasoiu",
    "Laurentiu Jitaru",
    "Adriana Micsa",
    "Mihai Sirb",
    "Stela Muncut",
    "Sorin Igret",
    "Radu Negrila",
    "Theoharis Babanatsas",
    "Andrei Komjaty",
    "Lavinia Culda",
  ];
  
  export const sectiuneaTextile = [
    "Ionel Barbu",
    "Cecilia Sirgie",
    "Monica Szabo",
    "Magdalena Fogorasi",
    "Monica Pustianu",
    "Erzsebet Airinei",
  ];